dist: trusty
sudo: require

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
before_install:
  - sudo apt-get install libboost-graph-dev

script:
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - make
